# This is a basic workflow to help you get started with Actions

name: KivySwiftLink release

# Controls when the workflow will run
on:
  push:
   tags: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mainjob1:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.var }}
    permissions:
        contents: write
    steps:
      - name: Set Version
        id: version
        run: |
            echo "var=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - name: Clone Github Repo
        # uses: whyakari/github-repo-action@809aeef1050b89b6f64d36fb9893c5e9ceaecbba
        uses: whyakari/github-repo-action@v3.1
        with:
          owner: PythonSwiftLink
          repository: KivySwiftLink
          access-token: ${{ secrets.ksl }}
          branch: master
      
        
      - name: repack
        run: python repack.py 


      # commit new package to kivypythoncore/master
      - name: commit KivyPythonCore to master
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ksl }}
        with:
          source-directory: 'PythonSwiftLink'
          destination-github-username: 'kivyswiftlink'
          destination-repository-name: 'PythonSwiftLink'
          user-email: pythonswiftlink@gmail.com
          target-branch: master

      - name: release PythonSwiftLink
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.var }}
          owner: kivyswiftlink
          repo: PythonSwiftLink
          token: ${{ secrets.ksl }}
          makeLatest: true

      
            
      
            
