# This is a basic workflow to help you get started with Actions

name: KivySwiftLink release

# Controls when the workflow will run
on:
  push:
   tags: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mainjob1:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:

      - uses: actions/checkout@v4

      